// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameUser = "users"

// User mapped from table <users>
type User struct {
	ID           string         `gorm:"column:id;primaryKey" json:"id"`
	Username     string         `gorm:"column:username;not null" json:"username"`
	PasswordHash string         `gorm:"column:password_hash;not null" json:"password_hash"`
	CreatedAt    time.Time      `gorm:"column:created_at" json:"created_at"`
	UpdatedAt    time.Time      `gorm:"column:updated_at" json:"updated_at"`
	DeletedAt    gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
	CreatedBy    string         `gorm:"column:created_by" json:"created_by"`
	UpdatedBy    string         `gorm:"column:updated_by" json:"updated_by"`
	DeletedBy    string         `gorm:"column:deleted_by" json:"deleted_by"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
