// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameRefreshToken = "refresh_tokens"

// RefreshToken mapped from table <refresh_tokens>
type RefreshToken struct {
	ID        string    `gorm:"column:id;primaryKey" json:"id"`
	UserID    string    `gorm:"column:user_id;not null" json:"user_id"`
	Token     string    `gorm:"column:token;not null" json:"token"`
	Revoked   bool      `gorm:"column:revoked" json:"revoked"`
	ExpiresAt time.Time `gorm:"column:expires_at;not null" json:"expires_at"`
	CreatedAt time.Time `gorm:"column:created_at" json:"created_at"`
}

// TableName RefreshToken's table name
func (*RefreshToken) TableName() string {
	return TableNameRefreshToken
}
